version: '3'

services:
  minio:
    image: minio/minio:RELEASE.2023-10-16T04-13-43Z
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - ./data:/kafka

